name: Publish Docker image - basic-http-hello-world

on:
  release:
    types: [published]
#  push:
#    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "eybon/basic-http-hello-world"
  IMAGE_VERSION_AMD64: "amd64"
  IMAGE_VERSION_ARMV7: "armv7"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push - version linux/amd64
        uses: docker/build-push-action@v5
        with:
          context: ./basic-http-hello-world
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_AMD64 }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push - version linux/arm/v7
        uses: docker/build-push-action@v5
        with:
          context: ./basic-http-hello-world
          push: true
          platforms: linux/arm/v7
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_ARMV7 }}
          labels: ${{ steps.meta.outputs.labels }}
